// Bundles the server into one ES module with no node_modules, for the plugin
// (plugins/susaplay/server/) and for npm (dist/). Both files are byte-identical.
//
// The plugin's copy is committed, and CI rebuilds it and fails if it differs, so
// the file developers run is always the one this source produces. Keep the
// output deterministic: no timestamps, no absolute paths, no source maps.
import { appendFile, chmod, copyFile, mkdir, readFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(await readFile(resolve(here, "package.json"), "utf8"));

const npmFile = resolve(here, "dist/susaplay-mcp.mjs");
const pluginFile = resolve(here, "../../plugins/susaplay/server/susaplay-mcp.mjs");

const result = await build({
  absWorkingDir: here,
  entryPoints: ["src/index.ts"],
  outfile: npmFile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "eof",
  define: { __SUSAPLAY_MCP_VERSION__: JSON.stringify(version) },
  // Some dependencies are CommonJS and call require(); an ES module has none.
  banner: {
    js: [
      "#!/usr/bin/env node",
      `// @susaplay/mcp ${version} — generated by packages/mcp-server/build.mjs. Do not edit.`,
      'import { createRequire as __susaplayCreateRequire } from "node:module";',
      "const require = __susaplayCreateRequire(import.meta.url);",
    ].join("\n"),
  },
  metafile: true,
  logLevel: "warning",
});

await appendFile(npmFile, await thirdPartyNotices(result.metafile));

// Every package that ended up in the bundle, with its license text, appended to
// the file. The bundle redistributes their code, and their licenses (MIT, ISC,
// Apache-2.0, BSD) ask for the notice to travel with it.
async function thirdPartyNotices(metafile) {
  const packages = new Map();
  for (const input of Object.keys(metafile.inputs)) {
    const parts = input.split(/[\\/]/);
    const at = parts.lastIndexOf("node_modules");
    if (at < 0) continue;
    const name = parts[at + 1]?.startsWith("@") ? `${parts[at + 1]}/${parts[at + 2]}` : parts[at + 1];
    const dir = resolve(here, ...parts.slice(0, at + 1 + name.split("/").length));
    packages.set(name, dir);
  }
  let text = "\n/*\n * Third-party software included in this file.\n";
  for (const name of [...packages.keys()].sort()) {
    const dir = packages.get(name);
    const meta = JSON.parse(await readFile(join(dir, "package.json"), "utf8"));
    const licenseFile = (await readdir(dir)).sort().find((file) => /^(licen[sc]e|copying)(\.|$)/i.test(file));
    const body = licenseFile
      ? (await readFile(join(dir, licenseFile), "utf8")).replaceAll("*/", "* /").trim()
      : `License: ${meta.license ?? "see the package"}`;
    text += ` *\n * ---- ${name} ${meta.version} (${meta.license ?? "unknown"}) ----\n *\n`;
    text += body.split(/\r?\n/).map((line) => ` * ${line}`.trimEnd()).join("\n") + "\n";
  }
  return `${text} */\n`;
}

await mkdir(dirname(pluginFile), { recursive: true });
await copyFile(npmFile, pluginFile);
// Executable everywhere: it is the package's `bin`, and git records the mode,
// so a mode that depended on the machine would fail the CI bundle check.
await chmod(npmFile, 0o755);
await chmod(pluginFile, 0o755);
console.log(`built @susaplay/mcp ${version}`);
